# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-06 16:23
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activitypub', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inbox',
            name='item',
        ),
        migrations.RemoveField(
            model_name='outbox',
            name='item',
        ),
        migrations.AddField(
            model_name='inbox',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default='a'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outbox',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default='a'),
            preserve_default=False,
        ),
    ]
